"""marca de envio exacto en recibo verificado

Revision ID: 153cd05ca071
Revises: 6f27004b320d
Create Date: 2026-08-07 14:40:00.223889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '153cd05ca071'
down_revision: Union[str, None] = '6f27004b320d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reciboverificado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enviado_sindicato', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('fecha_envio', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reciboverificado', schema=None) as batch_op:
        batch_op.drop_column('fecha_envio')
        batch_op.drop_column('enviado_sindicato')

    # ### end Alembic commands ###
