"""vigencia por fecha en Formula

Revision ID: 42994cc2b7f8
Revises: cd740d6bfadd
Create Date: 2026-08-10 19:15:35.996553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42994cc2b7f8'
down_revision: Union[str, None] = 'cd740d6bfadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_desde', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('fecha_hasta', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formula', schema=None) as batch_op:
        batch_op.drop_column('fecha_hasta')
        batch_op.drop_column('fecha_desde')

    # ### end Alembic commands ###
