"""token opaco de credencial para el QR

Revision ID: 67c8bb17017d
Revises: a36bfc5b0b9f
Create Date: 2026-08-10 16:51:02.370026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67c8bb17017d'
down_revision: Union[str, None] = 'a36bfc5b0b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_trabajador_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trabajador_token'))
        batch_op.drop_column('token')

    # ### end Alembic commands ###
