"""recibo verificado y detalle en envio sindicato

Revision ID: 6f27004b320d
Revises: a14ee8398d43
Create Date: 2026-08-07 14:26:09.702731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f27004b320d'
down_revision: Union[str, None] = 'a14ee8398d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reciboverificado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sindicato_id', sa.Integer(), nullable=False),
    sa.Column('cuil', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('periodo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sindicato_id'], ['sindicato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reciboverificado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reciboverificado_cuil'), ['cuil'], unique=False)
        batch_op.create_index(batch_op.f('ix_reciboverificado_sindicato_id'), ['sindicato_id'], unique=False)

    with op.batch_alter_table('enviosindicato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enviosindicato', schema=None) as batch_op:
        batch_op.drop_column('detalle')

    with op.batch_alter_table('reciboverificado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reciboverificado_sindicato_id'))
        batch_op.drop_index(batch_op.f('ix_reciboverificado_cuil'))

    op.drop_table('reciboverificado')
    # ### end Alembic commands ###
