"""categoria sindical y envio sindicato

Revision ID: a14ee8398d43
Revises: b9a4853cfe67
Create Date: 2026-08-05 20:22:07.735047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a14ee8398d43'
down_revision: Union[str, None] = 'b9a4853cfe67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enviosindicato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sindicato_id', sa.Integer(), nullable=False),
    sa.Column('cuil', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('periodo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monto_cuota', sa.Float(), nullable=False),
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['sindicato_id'], ['sindicato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enviosindicato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enviosindicato_cuil'), ['cuil'], unique=False)
        batch_op.create_index(batch_op.f('ix_enviosindicato_sindicato_id'), ['sindicato_id'], unique=False)

    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_sindical', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.drop_column('carga_sindical_convenio')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carga_sindical_convenio', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('categoria_sindical')

    with op.batch_alter_table('enviosindicato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enviosindicato_sindicato_id'))
        batch_op.drop_index(batch_op.f('ix_enviosindicato_cuil'))

    op.drop_table('enviosindicato')
    # ### end Alembic commands ###
