"""firma de la autoridad para la credencial sindical

Revision ID: a36bfc5b0b9f
Revises: 153cd05ca071
Create Date: 2026-08-10 15:41:37.751356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a36bfc5b0b9f'
down_revision: Union[str, None] = '153cd05ca071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sindicato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('firma_datos', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('firma_mime', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sindicato', schema=None) as batch_op:
        batch_op.drop_column('firma_mime')
        batch_op.drop_column('firma_datos')
        batch_op.drop_column('firma')

    # ### end Alembic commands ###
