"""codigo y vigencia de credencial persistidos

Revision ID: b2b614e9a572
Revises: 67c8bb17017d
Create Date: 2026-08-10 17:20:54.482604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2b614e9a572'
down_revision: Union[str, None] = '67c8bb17017d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_credencial', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('vigencia_credencial', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_trabajador_codigo_credencial'), ['codigo_credencial'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trabajador_codigo_credencial'))
        batch_op.drop_column('vigencia_credencial')
        batch_op.drop_column('codigo_credencial')

    # ### end Alembic commands ###
