"""tope sindical y carga sindical convenio

Revision ID: b9a4853cfe67
Revises: d22ab0e7eb3d
Create Date: 2026-08-05 19:16:11.476236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9a4853cfe67'
down_revision: Union[str, None] = 'd22ab0e7eb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracionplataforma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tope_sindical_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carga_sindical_convenio', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.drop_column('carga_sindical_convenio')

    op.drop_table('configuracionplataforma')
    # ### end Alembic commands ###
