"""esquema inicial

Revision ID: cbe17211376d
Revises: 
Create Date: 2026-08-03 18:13:37.562044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# JSONB en Postgres (indexable y consultable); JSON común en SQLite (no tiene jsonb).
# with_variant hace que el mismo tipo se materialice distinto según el motor.
JSON_TIPO = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


# revision identifiers, used by Alembic.
revision: str = 'cbe17211376d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentatrabajador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuil', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clave_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentatrabajador_cuil'), 'cuentatrabajador', ['cuil'], unique=True)
    op.create_table('sindicato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cuit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefonos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('autoridad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cargo_autoridad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_primario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_secundario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_acento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sindicato_slug'), 'sindicato', ['slug'], unique=False)
    op.create_table('concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sindicato_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remunerativo', sa.Boolean(), nullable=False),
    sa.Column('alias', JSON_TIPO, nullable=True),
    sa.Column('pendiente_revision', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sindicato_id'], ['sindicato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepto_codigo'), 'concepto', ['codigo'], unique=False)
    op.create_index(op.f('ix_concepto_sindicato_id'), 'concepto', ['sindicato_id'], unique=False)
    op.create_table('formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sindicato_id', sa.Integer(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tolerancia', sa.Float(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sindicato_id'], ['sindicato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formula_sindicato_id'), 'formula', ['sindicato_id'], unique=False)
    op.create_table('reporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sindicato_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cuil', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('periodo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detalle', JSON_TIPO, nullable=True),
    sa.ForeignKeyConstraint(['sindicato_id'], ['sindicato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_sindicato_id'), 'reporte', ['sindicato_id'], unique=False)
    op.create_table('trabajador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sindicato_id', sa.Integer(), nullable=False),
    sa.Column('cuil', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('piso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registrado', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sindicato_id'], ['sindicato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trabajador_cuil'), 'trabajador', ['cuil'], unique=False)
    op.create_index(op.f('ix_trabajador_sindicato_id'), 'trabajador', ['sindicato_id'], unique=False)
    op.create_table('usuariosindicato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sindicato_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clave_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('debe_cambiar_clave', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sindicato_id'], ['sindicato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuariosindicato_sindicato_id'), 'usuariosindicato', ['sindicato_id'], unique=False)
    op.create_index(op.f('ix_usuariosindicato_usuario'), 'usuariosindicato', ['usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuariosindicato_usuario'), table_name='usuariosindicato')
    op.drop_index(op.f('ix_usuariosindicato_sindicato_id'), table_name='usuariosindicato')
    op.drop_table('usuariosindicato')
    op.drop_index(op.f('ix_trabajador_sindicato_id'), table_name='trabajador')
    op.drop_index(op.f('ix_trabajador_cuil'), table_name='trabajador')
    op.drop_table('trabajador')
    op.drop_index(op.f('ix_reporte_sindicato_id'), table_name='reporte')
    op.drop_table('reporte')
    op.drop_index(op.f('ix_formula_sindicato_id'), table_name='formula')
    op.drop_table('formula')
    op.drop_index(op.f('ix_concepto_sindicato_id'), table_name='concepto')
    op.drop_index(op.f('ix_concepto_codigo'), table_name='concepto')
    op.drop_table('concepto')
    op.drop_index(op.f('ix_sindicato_slug'), table_name='sindicato')
    op.drop_table('sindicato')
    op.drop_index(op.f('ix_cuentatrabajador_cuil'), table_name='cuentatrabajador')
    op.drop_table('cuentatrabajador')
    # ### end Alembic commands ###
