"""cuit_empleador y codigo_generico en Concepto

Revision ID: cd740d6bfadd
Revises: b2b614e9a572
Create Date: 2026-08-10 18:12:16.680451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd740d6bfadd'
down_revision: Union[str, None] = 'b2b614e9a572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuit_empleador', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('codigo_generico', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_concepto_cuit_empleador'), ['cuit_empleador'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepto_cuit_empleador'))
        batch_op.drop_column('codigo_generico')
        batch_op.drop_column('cuit_empleador')

    # ### end Alembic commands ###
