"""logo en base (bytes + mime)

Revision ID: d22ab0e7eb3d
Revises: cbe17211376d
Create Date: 2026-08-03 18:36:09.222228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd22ab0e7eb3d'
down_revision: Union[str, None] = 'cbe17211376d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('concepto', 'alias',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('reporte', 'detalle',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('sindicato', sa.Column('logo_datos', sa.LargeBinary(), nullable=True))
    op.add_column('sindicato', sa.Column('logo_mime', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sindicato', 'logo_mime')
    op.drop_column('sindicato', 'logo_datos')
    op.alter_column('reporte', 'detalle',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('concepto', 'alias',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
