"""marca de plataforma: colores y logo

Revision ID: e7120b09b9f2
Revises: 42994cc2b7f8
Create Date: 2026-08-10 20:06:30.441285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7120b09b9f2'
down_revision: Union[str, None] = '42994cc2b7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracionplataforma', schema=None) as batch_op:
        # server_default: ya existe una fila (id=1, con tope_sindical_pct
        # cargado) y estas columnas son NOT NULL — sin default, Postgres
        # rechazaría el ALTER TABLE contra esa fila existente.
        batch_op.add_column(sa.Column('color_primario', sqlmodel.sql.sqltypes.AutoString(),
                                       nullable=False, server_default='#152238'))
        batch_op.add_column(sa.Column('color_secundario', sqlmodel.sql.sqltypes.AutoString(),
                                       nullable=False, server_default='#1a7a6b'))
        batch_op.add_column(sa.Column('color_acento', sqlmodel.sql.sqltypes.AutoString(),
                                       nullable=False, server_default='#b23a2e'))
        batch_op.add_column(sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(),
                                       nullable=False, server_default=''))
        batch_op.add_column(sa.Column('logo_datos', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('logo_mime', sqlmodel.sql.sqltypes.AutoString(),
                                       nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracionplataforma', schema=None) as batch_op:
        batch_op.drop_column('logo_mime')
        batch_op.drop_column('logo_datos')
        batch_op.drop_column('logo')
        batch_op.drop_column('color_acento')
        batch_op.drop_column('color_secundario')
        batch_op.drop_column('color_primario')

    # ### end Alembic commands ###
