"""Textos de la documentación que no salen solos del código: qué es cada
tabla, qué hace cada ruta y con qué rol, el inventario de módulos y scripts.
Relevado sobre el repo al 2026-09-07 (commit 8d3a657)."""

# ---------- Tablas: una línea cada una ----------
TABLAS = {
    "sindicato": "Raíz del multi-sindicato: marca (4 colores + destacado), logo y firma en bytes, contacto institucional, módulos habilitados y portadas.",
    "seccional": "Delegación o seccional de un sindicato; descriptiva, no afecta la validación ni el aislamiento.",
    "usuariosindicato": "Administrador de un sindicato (usuario = CUIT). Lo da de alta plataforma o el propio sindicato desde Administradores.",
    "cuentatrabajador": "Identidad global del trabajador: CUIL único + clave + foto. Con esto entra sin importar en cuántos sindicatos esté.",
    "trabajador": "Empadronamiento de un CUIL en un sindicato: una fila por gremio, con seccional, credencial (token del QR, código visible, vigencia) y el último semáforo.",
    "cuentaempleador": "Identidad global del empleador: CUIT único + clave + foto. Espejo de cuentatrabajador.",
    "empleador": "Alta de un CUIT como empresa en un sindicato (el CRUD del admin). Un CUIT puede estar en varios.",
    "concepto": "Ítem del recibo (ingreso o descuento) que el validador reconoce: código, alias, remunerativo, categoría sindical, específico de un CUIT o genérico.",
    "formula": "Regla que controla un concepto genérico: expresión, tolerancia, vigencia por período y si se recorta al tope de seguridad social.",
    "topebaseimponible": "Tope máximo y piso mínimo de la base imponible por vigencia mensual (art. 9 Ley 24.241). Nacional, lo administra plataforma.",
    "reporte": "Recibo que el trabajador reportó al sindicato, con el detalle completo.",
    "enviosindicato": "Envío voluntario del recibo para acreditar afiliado cotizante (art. 21 bis). No se anonimiza.",
    "reciboverificado": "Historial privado del trabajador: cada recibo verificado, con columnas analíticas para el Panel Sindical.",
    "recibosospechoso": "Recibo que la IA marcó con señales de adulteración; guarda el archivo original y lo ve solo plataforma.",
    "usoia": "Una fila por llamada a la API de Anthropic: tipo, modelo y tokens reales, para medir costo por sindicato.",
    "noticia": "Novedad del sindicato con vigencia cerrada, hasta dos imágenes, destino por seccionales y formulario para iniciar.",
    "beneficio": "Descuento o beneficio para afiliados: rubro, imagen, link, vigencia, seccionales.",
    "notificacion": "Mensaje dirigido del sindicato a trabajadores; los destinatarios se fijan al enviar.",
    "notificaciondestinatario": "Un CUIL que recibió una notificación y cuándo la leyó.",
    "notificacionempleador": "Espejo de notificacion para empresas, en tabla separada a propósito.",
    "notificacionempleadordestinatario": "Un CUIT destinatario de una notificación a empresas y su lectura.",
    "tipotramite": "Formulario que el sindicato ofrece al trabajador: título, código del expediente y reglas de consistencia.",
    "campotramite": "Un campo del formulario dinámico: tipo de dato, ancho, obligatorio, validaciones; retirado si tiene respuestas.",
    "tramite": "Expediente presentado por un trabajador, correlativo por tipo, con cinco estados y marca de visto.",
    "respuestatramite": "Lo que el trabajador cargó en cada campo, archivo incluido.",
    "notatramite": "Chat del expediente: notas de admin y trabajador con adjunto opcional.",
    "tramitelog": "Un evento por fila del expediente (creado, cambio de estado, notas).",
    "tipotramiteempleador": "Espejo de tipotramite para trámites externos de empresas.",
    "campotramiteempleador": "Espejo de campotramite.",
    "tramiteempleador": "Espejo de tramite, por CUIT, con visto_empresa_en.",
    "respuestatramiteempleador": "Espejo de respuestatramite.",
    "notatramiteempleador": "Espejo de notatramite; el autor es admin o empresa.",
    "tramiteempleadorlog": "Espejo de tramitelog.",
    "configuracionplataforma": "Fila única: tope sindical, umbrales del semáforo por empresa, flag del carril de consultas, marca y logos de Colm3na.",
    "consultaasistente": "Cada pregunta al Asistente del Panel: qué se preguntó, qué contestó, qué filtros quedaron y cuánto costó.",
    "convenio": "Un convenio colectivo del sindicato; el trabajador elige cuál consultar.",
    "documentoconvenio": "El PDF del convenio o de un acta, con vigencia declarada por el admin y estado de indexación.",
    "fragmentoconvenio": "Un trozo indexado con su vector de 1024 dimensiones; sindicato_id desnormalizado para filtrar en la búsqueda.",
    "consultaconvenio": "Cada pregunta de un trabajador al convenio, con los fragmentos usados y si hubo respuesta.",
    "suscripcionpush": "Suscripción Web Push de un navegador del trabajador; se borra sola cuando el endpoint muere.",
    "recurso": "Documentación del proyecto subida desde la landing /entornos: archivo o enlace, miniatura y fecha.",
}

# ---------- Rutas: (grupo, rol, qué hace) ----------
GRUPOS = [
    ("publico", "Público, assets y PWA"), ("trab-acceso", "Trabajador: acceso, perfil y credencial"),
    ("trab-recibos", "Recibos, validación y aportes"), ("trab-novedades", "Noticias y beneficios"),
    ("trab-notif", "Notificaciones del trabajador"), ("trab-push", "Web Push"), ("trab-tramites", "Trámites del trabajador"),
    ("trab-convenio", "Convenio (RAG) del trabajador"), ("admin-acceso", "Sindicato: acceso y páginas"),
    ("admin-padron", "Sindicato: padrón"), ("admin-usuarios", "Sindicato: administradores"),
    ("admin-catalogo", "Sindicato: conceptos, fórmulas y aprendizaje"), ("admin-contenido", "Sindicato: noticias, beneficios y seccionales"),
    ("admin-notif", "Sindicato: notificaciones a trabajadores"), ("admin-tramites", "Sindicato: trámites de trabajadores"),
    ("admin-empleadores", "Sindicato: empleadores"), ("admin-notif-emp", "Sindicato: notificaciones a empresas"),
    ("admin-tramites-emp", "Sindicato: trámites de empresas"), ("admin-convenio", "Sindicato: convenio y RAG"),
    ("dashboard", "Panel Sindical"), ("plataforma", "Plataforma"), ("empresa", "Empresa"), ("interno", "Entornos y Recursos (interno)"),
]
RUTAS = {
    ("GET", "/sw.js"): ("publico", "público", "Service worker de la PWA, servido desde la raíz para poder pedir scope /app."),
    ("GET", "/logo/{sindicato_id}"): ("publico", "público", "Logo del sindicato guardado en la base."),
    ("GET", "/firma/{sindicato_id}"): ("publico", "público", "Firma digitalizada de la autoridad, para la credencial."),
    ("GET", "/noticia-imagen/{noticia_id}/{n}"): ("publico", "público", "Imagen 1 o 2 de una noticia."),
    ("GET", "/beneficio-imagen/{beneficio_id}"): ("publico", "público", "Imagen del beneficio del carrusel."),
    ("GET", "/logo-plataforma"): ("publico", "público", "Logo de plataforma para fondo claro."),
    ("GET", "/logo-plataforma-oscuro"): ("publico", "público", "Logo de plataforma para fondo oscuro."),
    ("GET", "/"): ("publico", "público", "Demo anónima: la app del trabajador con solo el módulo recibos."),
    ("GET", "/api/version"): ("publico", "público", "Versión de cada app y entorno, JSON con CORS abierto."),
    ("GET", "/v/{token}"): ("publico", "público", "Verificación de la credencial detrás del QR; sin código efímero vigente no muestra nada."),
    ("GET", "/ingresar"): ("trab-acceso", "público", "Pantalla de login y registro del trabajador."),
    ("POST", "/trabajador/login"): ("trab-acceso", "público", "Valida CUIL + clave, crea la sesión y la cookie de identidad."),
    ("POST", "/trabajador/registro"): ("trab-acceso", "público", "Autorregistro; exige estar empadronado en al menos un sindicato."),
    ("GET", "/app"): ("trab-acceso", "trabajador", "Panel de seis pestañas; si está en varios sindicatos y no eligió, el selector."),
    ("GET", "/app/inicio"): ("trab-acceso", "trabajador", "Portada de tarjetas, novedades y beneficios."),
    ("GET", "/app/elegir/{sindicato_id}"): ("trab-acceso", "trabajador", "Fija el sindicato activo."),
    ("GET", "/app/cambiar"): ("trab-acceso", "trabajador", "Vuelve al selector de sindicato."),
    ("GET", "/trabajador/salir"): ("trab-acceso", "trabajador", "Cierra la sesión y limpia sus tres cookies."),
    ("POST", "/api/perfil"): ("trab-acceso", "trabajador", "Edita el perfil (todo menos el CUIL) en el sindicato activo."),
    ("POST", "/api/perfil/foto"): ("trab-acceso", "trabajador", "Sube la foto de perfil, una por CUIL."),
    ("GET", "/perfil-foto/{cuil}"): ("trab-acceso", "trabajador · sindicato", "Foto de perfil: la ve el dueño o el admin donde ese CUIL está empadronado."),
    ("GET", "/api/credencial/qr"): ("trab-acceso", "trabajador", "Emite un QR nuevo con código efímero de diez minutos."),
    ("POST", "/api/leer"): ("trab-recibos", "trabajador · público", "La IA lee el recibo (foto o PDF), formato clásico o Anexo III."),
    ("POST", "/api/validar"): ("trab-recibos", "trabajador · público", "Valida los aportes contra las fórmulas y guarda el ReciboVerificado."),
    ("POST", "/api/reportar"): ("trab-recibos", "trabajador", "Guarda el recibo y su resultado como reporte al sindicato."),
    ("POST", "/api/enviar-sindicato"): ("trab-recibos", "trabajador", "Envío voluntario con disclaimer: acredita afiliado cotizante."),
    ("GET", "/api/mis-recibos"): ("trab-recibos", "trabajador", "Historial privado de recibos verificados."),
    ("POST", "/api/aportes"): ("trab-recibos", "trabajador", "Lee el comprobante de ARCA con IA y persiste el semáforo."),
    ("GET", "/api/noticia/{noticia_id}"): ("trab-novedades", "trabajador", "Detalle de una noticia para el modal."),
    ("GET", "/api/beneficio/{beneficio_id}"): ("trab-novedades", "trabajador", "Detalle de un beneficio para el modal."),
    ("GET", "/app/notificaciones"): ("trab-notif", "trabajador", "Bandeja de notificaciones."),
    ("GET", "/api/mis-notificaciones"): ("trab-notif", "trabajador", "Sus notificaciones en JSON."),
    ("POST", "/api/notificacion/{notificacion_id}/leer"): ("trab-notif", "trabajador", "Marca una como leída."),
    ("POST", "/api/notificaciones/leer-todas"): ("trab-notif", "trabajador", "Marca todas como leídas."),
    ("GET", "/notificacion-adjunto/{notificacion_id}"): ("trab-notif", "trabajador · sindicato", "Adjunto: el admin que la mandó o un destinatario real."),
    ("GET", "/api/push/clave-publica"): ("trab-push", "trabajador", "Clave pública VAPID; vacía significa push apagado."),
    ("POST", "/api/push/suscribir"): ("trab-push", "trabajador", "Registra la suscripción del navegador."),
    ("POST", "/api/push/desuscribir"): ("trab-push", "trabajador", "Da de baja la suscripción."),
    ("GET", "/api/tramites/tipos"): ("trab-tramites", "trabajador", "Formularios activos de su sindicato."),
    ("GET", "/api/tramites/mios"): ("trab-tramites", "trabajador", "Sus expedientes con estado y novedades."),
    ("GET", "/api/tramite/{numero_expediente}"): ("trab-tramites", "trabajador", "Consulta un expediente por número."),
    ("GET", "/api/tramites/novedades"): ("trab-tramites", "trabajador", "Cantidad con movimientos sin ver, para el globo."),
    ("POST", "/api/tramite"): ("trab-tramites", "trabajador", "Envía un trámite: campos dinámicos, archivos y validaciones."),
    ("POST", "/api/tramite/{tramite_id}/nota"): ("trab-tramites", "trabajador", "Responde en el chat del expediente."),
    ("GET", "/tramite-respuesta-archivo/{respuesta_id}"): ("trab-tramites", "trabajador · sindicato", "Archivo cargado en un campo del formulario."),
    ("GET", "/tramite-nota-adjunto/{nota_id}"): ("trab-tramites", "trabajador · sindicato", "Adjunto de una nota del chat."),
    ("GET", "/app/convenio"): ("trab-convenio", "trabajador", "Pantalla del piloto de consultas; no está en el menú."),
    ("GET", "/api/convenio/convenios"): ("trab-convenio", "trabajador", "Convenios que puede consultar."),
    ("POST", "/api/convenio/consultar"): ("trab-convenio", "trabajador", "Búsqueda vectorial y respuesta citando el artículo."),
    ("GET", "/admin"): ("admin-acceso", "sindicato", "Panel de quince pestañas; sin sesión, el login."),
    ("GET", "/admin/inicio"): ("admin-acceso", "sindicato", "Portada de tarjetas."),
    ("POST", "/admin/login"): ("admin-acceso", "público", "CUIT + clave contra UsuarioSindicato."),
    ("GET", "/admin/salir"): ("admin-acceso", "sindicato", "Cierra la sesión."),
    ("GET", "/admin/dashboard"): ("admin-acceso", "sindicato", "Página del Panel Sindical; sin módulo, vuelve a /admin."),
    ("POST", "/admin/trabajador"): ("admin-padron", "sindicato", "Alta o edición de un trabajador."),
    ("POST", "/admin/trabajador/generar-credencial"): ("admin-padron", "sindicato", "Genera o regenera el código de credencial."),
    ("POST", "/admin/trabajador/masivo"): ("admin-padron", "sindicato", "Alta masiva por líneas separadas por coma."),
    ("POST", "/admin/trabajador/baja"): ("admin-padron", "sindicato", "Baja lógica."),
    ("POST", "/admin/trabajador/alta-logica"): ("admin-padron", "sindicato", "Reactiva un trabajador."),
    ("POST", "/admin/usuario"): ("admin-usuarios", "sindicato", "Alta de un administrador del propio sindicato."),
    ("POST", "/admin/usuario/editar"): ("admin-usuarios", "sindicato", "Edita el nombre."),
    ("POST", "/admin/usuario/baja"): ("admin-usuarios", "sindicato", "Baja lógica; bloqueada si es el último activo."),
    ("POST", "/admin/usuario/alta-logica"): ("admin-usuarios", "sindicato", "Reactiva."),
    ("POST", "/admin/concepto"): ("admin-catalogo", "sindicato", "Alta o edición de concepto."),
    ("POST", "/admin/concepto/borrar"): ("admin-catalogo", "sindicato", "Borra un concepto."),
    ("POST", "/admin/concepto/confirmar"): ("admin-catalogo", "sindicato", "Saca la marca «por revisar»."),
    ("POST", "/admin/concepto/fusionar"): ("admin-catalogo", "sindicato", "Fusiona un provisorio contra uno existente."),
    ("POST", "/admin/conceptos-universales"): ("admin-catalogo", "sindicato", "Carga idempotente de jubilación, PAMI y obra social."),
    ("POST", "/admin/formula"): ("admin-catalogo", "sindicato", "Alta o edición; prueba la expresión antes de guardar."),
    ("POST", "/admin/formula/borrar"): ("admin-catalogo", "sindicato", "Borra una fórmula."),
    ("POST", "/admin/aprender"): ("admin-catalogo", "sindicato", "Lee varios recibos con IA y propone conceptos nuevos."),
    ("POST", "/admin/aprender/aplicar"): ("admin-catalogo", "sindicato", "Da de alta en lote los conceptos aprobados."),
    ("POST", "/admin/noticia"): ("admin-contenido", "sindicato", "Alta o edición de noticia."),
    ("POST", "/admin/noticia/borrar"): ("admin-contenido", "sindicato", "Borra una noticia."),
    ("POST", "/admin/beneficio"): ("admin-contenido", "sindicato", "Alta o edición de beneficio."),
    ("POST", "/admin/beneficio/borrar"): ("admin-contenido", "sindicato", "Borra un beneficio."),
    ("POST", "/admin/seccional"): ("admin-contenido", "sindicato", "Alta o edición de seccional."),
    ("POST", "/admin/seccional/borrar"): ("admin-contenido", "sindicato", "Borra la seccional; los trabajadores quedan sin seccional."),
    ("POST", "/admin/notificacion/preview"): ("admin-notif", "sindicato", "Cuenta destinatarios sin persistir nada."),
    ("POST", "/admin/notificacion"): ("admin-notif", "sindicato", "Envía la notificación dirigida, con adjunto."),
    ("GET", "/admin/notificacion/{notificacion_id}/destinatarios"): ("admin-notif", "sindicato", "Quién la recibió y si la leyó."),
    ("POST", "/admin/tramite-tipo"): ("admin-tramites", "sindicato", "Alta o edición de un tipo de trámite con sus campos y validaciones."),
    ("POST", "/admin/tramite-tipo/probar"): ("admin-tramites", "sindicato", "Banco de pruebas del constructor: el mismo motor que el envío real."),
    ("POST", "/admin/tramite-tipo/borrar"): ("admin-tramites", "sindicato", "Borra un tipo."),
    ("GET", "/admin/tramite/{tramite_id}"): ("admin-tramites", "sindicato", "Detalle completo de un expediente."),
    ("GET", "/admin/tramites-nuevos-cantidad"): ("admin-tramites", "sindicato", "Polling del globo de trámites nuevos."),
    ("POST", "/admin/tramite/{tramite_id}/estado"): ("admin-tramites", "sindicato", "Cambia el estado; un terminado queda bloqueado."),
    ("POST", "/admin/tramite/{tramite_id}/nota"): ("admin-tramites", "sindicato", "Escribe en el chat, con adjunto o formulario."),
    ("POST", "/admin/empleador"): ("admin-empleadores", "sindicato", "Alta o edición de una empresa."),
    ("POST", "/admin/empleador/baja"): ("admin-empleadores", "sindicato", "Baja lógica."),
    ("POST", "/admin/empleador/alta-logica"): ("admin-empleadores", "sindicato", "Reactiva."),
    ("POST", "/admin/empleador/importar-cuits"): ("admin-empleadores", "sindicato", "Crea empleadores a partir de los CUITs de los conceptos."),
    ("POST", "/admin/notificacion-empresa/preview"): ("admin-notif-emp", "sindicato", "Cuenta destinatarios (CUITs)."),
    ("POST", "/admin/notificacion-empresa"): ("admin-notif-emp", "sindicato", "Envía la notificación a empresas."),
    ("GET", "/admin/notificacion-empresa/{notificacion_empleador_id}/destinatarios"): ("admin-notif-emp", "sindicato", "Destinatarios y lecturas."),
    ("GET", "/notificacion-empresa-adjunto/{notificacion_empleador_id}"): ("admin-notif-emp", "sindicato · empresa", "Adjunto: el admin que la mandó o un destinatario real."),
    ("POST", "/admin/tramite-tipo-empresa"): ("admin-tramites-emp", "sindicato", "Alta o edición de tipo de trámite externo."),
    ("POST", "/admin/tramite-tipo-empresa/borrar"): ("admin-tramites-emp", "sindicato", "Borra el tipo."),
    ("GET", "/admin/tramite-empresa/{tramite_id}"): ("admin-tramites-emp", "sindicato", "Detalle del expediente de una empresa."),
    ("GET", "/admin/tramites-empresa-nuevos-cantidad"): ("admin-tramites-emp", "sindicato", "Polling del globo."),
    ("POST", "/admin/tramite-empresa/{tramite_id}/estado"): ("admin-tramites-emp", "sindicato", "Cambia el estado."),
    ("POST", "/admin/tramite-empresa/{tramite_id}/nota"): ("admin-tramites-emp", "sindicato", "Escribe en el chat con la empresa."),
    ("GET", "/tramite-empresa-respuesta-archivo/{respuesta_id}"): ("admin-tramites-emp", "sindicato · empresa", "Archivo de un campo del formulario."),
    ("GET", "/tramite-empresa-nota-adjunto/{nota_id}"): ("admin-tramites-emp", "sindicato · empresa", "Adjunto de una nota."),
    ("POST", "/admin/convenio"): ("admin-convenio", "sindicato", "Alta o edición de un convenio."),
    ("POST", "/admin/convenio/documento"): ("admin-convenio", "sindicato", "Sube un PDF y lanza la indexación en un hilo."),
    ("GET", "/admin/convenio/documento/{documento_id}/estado"): ("admin-convenio", "sindicato", "Progreso de la indexación."),
    ("GET", "/admin/convenio/documento/{documento_id}/fragmentos"): ("admin-convenio", "sindicato", "Vista previa del troceo con texto real."),
    ("POST", "/admin/convenio/documento/{documento_id}/vigencia"): ("admin-convenio", "sindicato", "Marca vigente o no vigente."),
    ("POST", "/admin/convenio/documento/{documento_id}/borrar"): ("admin-convenio", "sindicato", "Borra el documento y sus fragmentos."),
    ("POST", "/admin/convenio/documento/{documento_id}/reindexar"): ("admin-convenio", "sindicato", "Rehace troceo y embeddings."),
    ("GET", "/admin/convenio/{convenio_id}/anteriores"): ("admin-convenio", "sindicato", "Documentos vigentes anteriores a una fecha."),
    ("POST", "/admin/dashboard/asistente"): ("dashboard", "sindicato", "Pregunta en lenguaje natural: filtros del panel más resumen."),
    ("GET", "/admin/dashboard/kpis"): ("dashboard", "sindicato", "Los diez KPIs de la fila superior."),
    ("GET", "/admin/dashboard/serie-recibos"): ("dashboard", "sindicato", "Serie diaria de recibos procesados."),
    ("GET", "/admin/dashboard/validacion"): ("dashboard", "sindicato", "En orden vs. con diferencias."),
    ("GET", "/admin/dashboard/diferencias-empresa"): ("dashboard", "sindicato", "Top de empresas por monto observado."),
    ("GET", "/admin/dashboard/tramites-seccional"): ("dashboard", "sindicato", "Trámites por seccional y estado."),
    ("GET", "/admin/dashboard/notificaciones"): ("dashboard", "sindicato", "Leídas vs. no leídas por tipo."),
    ("GET", "/admin/dashboard/formato-semana"): ("dashboard", "sindicato", "Adopción del formato Ley 27.802 por semana."),
    ("GET", "/admin/dashboard/semaforo"): ("dashboard", "sindicato", "Semáforo de aportes por empresa."),
    ("GET", "/admin/dashboard/consultas"): ("dashboard", "sindicato", "Temas consultados al bot; 404 con el flag apagado."),
    ("GET", "/admin/dashboard/explorador/{fuente}"): ("dashboard", "sindicato", "Explorador paginado por fuente."),
    ("GET", "/admin/dashboard/detalle/recibo/{recibo_id}"): ("dashboard", "sindicato", "Modal de un recibo, anonimizado si no fue enviado."),
    ("GET", "/admin/dashboard/detalle/tramite/{tramite_id}"): ("dashboard", "sindicato", "Modal de un trámite."),
    ("GET", "/admin/dashboard/detalle/notificaciones"): ("dashboard", "sindicato", "Notificaciones de un día, tipo o seccional."),
    ("GET", "/admin/dashboard/detalle/notificacion/{notificacion_id}/destinatarios"): ("dashboard", "sindicato", "Quién la recibió y cuándo la leyó."),
    ("GET", "/admin/dashboard/detalle/consulta/{consulta_id}"): ("dashboard", "sindicato", "Detalle de una consulta al bot."),
    ("GET", "/admin/dashboard/afiliados"): ("dashboard", "sindicato", "Buscador del filtro por afiliado."),
    ("GET", "/admin/dashboard/filtros"): ("dashboard", "sindicato", "Catálogos de filtros: seccionales, empresas, categorías, rango de bruto."),
    ("GET", "/plataforma"): ("plataforma", "plataforma", "Panel de nueve pestañas; sin sesión, el login."),
    ("GET", "/plataforma/inicio"): ("plataforma", "plataforma", "Portada de tarjetas."),
    ("POST", "/plataforma/login"): ("plataforma", "público", "CUIT + clave de entorno."),
    ("GET", "/plataforma/salir"): ("plataforma", "plataforma", "Cierra la sesión."),
    ("POST", "/plataforma/config"): ("plataforma", "plataforma", "Fija el tope de cuota sindical."),
    ("POST", "/plataforma/config-dashboard"): ("plataforma", "plataforma", "Umbrales del semáforo y flag de consultas."),
    ("POST", "/plataforma/tope"): ("plataforma", "plataforma", "Alta o edición de un tope de base imponible."),
    ("POST", "/plataforma/tope/borrar"): ("plataforma", "plataforma", "Borra un tope."),
    ("POST", "/plataforma/marca"): ("plataforma", "plataforma", "Logos y colores de la plataforma."),
    ("POST", "/plataforma/sindicato"): ("plataforma", "plataforma", "Alta de un sindicato con marca, logo, firma y módulos."),
    ("POST", "/plataforma/sindicato/editar"): ("plataforma", "plataforma", "Edita todo lo anterior."),
    ("POST", "/plataforma/sindicato/borrar"): ("plataforma", "plataforma", "Borra el sindicato y todos sus datos."),
    ("POST", "/plataforma/usuario"): ("plataforma", "plataforma", "Crea un admin de sindicato."),
    ("GET", "/plataforma/admins/{sindicato_id}"): ("plataforma", "plataforma", "Admins de ese sindicato."),
    ("GET", "/plataforma/trabajadores/{sindicato_id}"): ("plataforma", "plataforma", "Trabajadores empadronados."),
    ("POST", "/plataforma/reset-clave"): ("plataforma", "plataforma", "Transitorio: cambia la clave de cualquier usuario."),
    ("GET", "/plataforma/recibos-sospechosos/{recibo_id}/archivo"): ("plataforma", "plataforma", "Archivo original de un recibo con alerta."),
    ("GET", "/ingresar-empresa"): ("empresa", "público", "Login y registro del empleador."),
    ("POST", "/empresa/login"): ("empresa", "público", "CUIT + clave."),
    ("POST", "/empresa/registro"): ("empresa", "público", "Autorregistro; exige estar de alta como empleador activo."),
    ("GET", "/empresa/inicio"): ("empresa", "empresa", "Portada con perfil y dos tarjetas."),
    ("GET", "/empresa"): ("empresa", "empresa", "Panel de dos pestañas; selector si está en varios sindicatos."),
    ("GET", "/empresa/elegir/{sindicato_id}"): ("empresa", "empresa", "Fija el sindicato activo."),
    ("GET", "/empresa/cambiar"): ("empresa", "empresa", "Vuelve al selector."),
    ("GET", "/empresa/salir"): ("empresa", "empresa", "Cierra la sesión."),
    ("POST", "/api/empresa/perfil"): ("empresa", "empresa", "Edita el perfil (todo menos el CUIT)."),
    ("POST", "/api/empresa/perfil/foto"): ("empresa", "empresa", "Foto de perfil, una por CUIT."),
    ("GET", "/perfil-empleador-foto/{cuit}"): ("empresa", "empresa · sindicato", "Foto de la empresa."),
    ("GET", "/api/empresa/notificaciones"): ("empresa", "empresa", "Sus notificaciones."),
    ("POST", "/api/empresa/notificacion/{notificacion_empleador_id}/leer"): ("empresa", "empresa", "Marca una como leída."),
    ("GET", "/api/empresa/tramites/tipos"): ("empresa", "empresa", "Formularios externos activos."),
    ("GET", "/api/empresa/tramites/mios"): ("empresa", "empresa", "Sus expedientes."),
    ("GET", "/api/empresa/tramite/{numero_expediente}"): ("empresa", "empresa", "Consulta por número."),
    ("GET", "/api/empresa/tramites/novedades"): ("empresa", "empresa", "Globo de novedades."),
    ("POST", "/api/empresa/tramite"): ("empresa", "empresa", "Envía un trámite externo con las mismas validaciones."),
    ("POST", "/api/empresa/tramite/{tramite_id}/nota"): ("empresa", "empresa", "Responde en el chat del expediente."),
    ("GET", "/entornos"): ("interno", "interno", "Landing de accesos, versiones y Recursos; sin pase, la pantalla del PIN."),
    ("POST", "/entornos/pin"): ("interno", "interno", "Valida el PIN de ocho dígitos y deja el pase de treinta días."),
    ("POST", "/recursos"): ("interno", "interno", "Sube un recurso con miniatura y descripción."),
    ("POST", "/recursos/{recurso_id}/quitar"): ("interno", "interno", "Quita un recurso subido."),
    ("GET", "/recursos/{ref}/archivo"): ("interno", "interno", "Abre el recurso; acepta rangos para adelantar video."),
    ("GET", "/recursos/{ref}/miniatura"): ("interno", "interno", "Miniatura del recurso."),
}

# ---------- Módulos de Python ----------
MODULOS = [
    ("main.py", "211 KB", "Servidor FastAPI y todas las rutas (172). Middlewares de cache y renovación de sesión, manejadores de error, guardas de módulo, globals de Jinja."),
    ("db.py", "160 KB", "Los 41 modelos SQLModel, el engine dual Postgres/SQLite y todo el acceso a datos."),
    ("auth.py", "3 KB", "PBKDF2-HMAC-SHA256 para claves; sesiones como token firmado HMAC en cookie; 15 minutos sin uso."),
    ("extractor.py", "11 KB", "Lee recibos y comprobantes de ARCA con Claude Sonnet 4.6; PDF a PNG con pdf2image."),
    ("validador.py", "35 KB", "Motor de validación: matching de conceptos, fórmulas vigentes por período, topes de seguridad social, categorías universales. Sin dependencias externas."),
    ("semaforo.py", "4 KB", "Color global y conteos del semáforo ARCA; alerta temprana por fecha del último depósito."),
    ("dashboard.py", "49 KB", "Agregados SQL del Panel Sindical, explorador paginado y detalle por fila; filtros parseados una sola vez."),
    ("asistente.py", "30 KB", "Asistente del Panel: la pregunta se traduce a filtros con Claude Sonnet 5 y se resume con los números reales."),
    ("rag.py", "23 KB", "Convenio: extracción del PDF, troceo, embeddings locales con fastembed, indexación en hilo, búsqueda y respuesta con Claude Opus 5."),
    ("validaciones_tramite.py", "11 KB", "Motor puro de validaciones de formularios: fuente fija y consistencia entre campos. La única implementación, la usan el envío real y el banco de pruebas."),
    ("push.py", "3 KB", "Web Push a la PWA; envío en un hilo, limpia suscripciones muertas. Apagado en silencio sin claves VAPID."),
    ("qr.py", "4 KB", "QR de la credencial como SVG (segno) con código efímero de diez minutos firmado."),
    ("filigrana.py", "4 KB", "Guilloche SVG determinística por sindicato para el fondo de la credencial."),
    ("recursos.py", "11 KB", "Catálogo de la landing /entornos (repo más base), el pase de treinta días del PIN y la clasificación por tipo."),
    ("errores.py", "5 KB", "Catálogo de códigos de error propios y la excepción ErrorApp."),
    ("modulos.py", "2 KB", "Catálogo de los once módulos habilitables por sindicato y los seis iniciales."),
    ("entorno.py", "2 KB", "Entorno en curso, distintivo, URLs de los dos servicios y el PIN de la landing."),
    ("version.py", "0,5 KB", "Versión de cada app y fecha del último cambio."),
    ("pg_cliente.py", "3 KB", "Elige un pg_dump y pg_restore compatibles con el Postgres de Render."),
]
SCRIPTS = [
    ("promover_demo.py", "Backup de la base de demo, merge main → demo, tag y push. La única forma de cambiar la demo."),
    ("clonar_demo_a_pruebas.py", "Excepción: clona la demo entera a Pruebas con tres guardas; excluye la tabla recurso."),
    ("cargar_marca_plataforma.py", "Siembra logo y colores de Colm3na en la base. Va primero al poblar un entorno."),
    ("cargar_demo.py", "Dos sindicatos de demo desde cero, con marca, admins, conceptos, fórmulas y trabajadores."),
    ("cargar_lote_sindicato.py", "Lote sintético completo para cualquier sindicato: 6 seccionales, 100 trabajadores, 5.000 recibos autocorregidos, 2.000 trámites, notificaciones, noticias y beneficios."),
    ("cargar_bancaria.py", "Alta de La Bancaria con los conceptos del CCT 18/75 y su lote."),
    ("cargar_lote_uom.py", "Versión anterior del lote, específica de la UOM."),
    ("chequeo.py", "Autodiagnóstico de la instalación; se detiene en el primer problema y dice qué hacer."),
    ("medir_dashboard.py", "50.000 recibos sintéticos y cronómetro de cada endpoint del panel; criterio menor a un segundo."),
    ("probar_asistente.py", "Set de aceptación del prompt del Asistente contra la API real; gasta créditos, nunca en CI."),
]
TEMPLATES = [
    ("Trabajador", [("trabajador_login.html", "/ingresar", "Login por CUIL"), ("elegir_sindicato.html", "/app", "Selector cuando está en varios sindicatos"),
                    ("portada.html", "/app/inicio", "Portada: tarjetas, novedades y carrusel de beneficios"), ("trabajador.html", "/app", "El panel de seis pestañas; 139 KB, el más grande de la suite"),
                    ("notificaciones.html", "/app/notificaciones", "Bandeja tipo hilo"), ("convenio.html", "/app/convenio", "Consultas al convenio (piloto)"),
                    ("verificar_credencial.html", "/v/{token}", "Verificación pública de la credencial")]),
    ("Sindicato", [("admin_login.html", "/admin", "Login por CUIT"), ("admin_portada.html", "/admin/inicio", "Portada de tarjetas"),
                   ("admin.html", "/admin", "Panel de quince pestañas; 244 KB, el archivo más grande del repo"), ("dashboard.html", "/admin/dashboard", "Panel Sindical con Asistente")]),
    ("Empresa", [("empresa_login.html", "/ingresar-empresa", "Login y autorregistro"), ("elegir_sindicato_empresa.html", "/empresa/inicio", "Selector multisindicato"),
                 ("empresa_portada.html", "/empresa/inicio", "Portada"), ("empresa.html", "/empresa", "Panel de dos pestañas")]),
    ("Plataforma", [("plataforma_login.html", "/plataforma", "Login"), ("plataforma_portada.html", "/plataforma/inicio", "Portada"), ("plataforma.html", "/plataforma", "Panel de nueve pestañas")]),
    ("Interno", [("_entorno.html", "incluido", "Distintivo de entorno"), ("entornos_pin.html", "/entornos", "Puerta del PIN"), ("entornos.html", "/entornos", "Landing de accesos y Recursos")]),
]
STATIC = [
    ("marca.css", "Sistema de diseño compartido: cuatro colores por sindicato, grises fijos, estados que nunca toman la marca, radios y logos a 76 px."),
    ("dashboard.js", "Panel Sindical: estado de filtros, una ronda de fetches en paralelo por cambio, cross-filtering. Solo pinta."),
    ("pwa.js · sw.js · manifest.json", "PWA instalable. El service worker no cachea nada a propósito: con deploy en cada push, cachear dejaría al trabajador en una versión vieja."),
    ("chart.umd.min.js", "Chart.js 4.4.9 vendoreado; nunca CDN."),
    ("fonts/barlow-condensed-bold.woff2", "La display de títulos, alojada local."),
    ("marca/ · icons/ · colmena_dorada.webp", "Logos oficiales de Colm3na, íconos de la PWA y la colmena de la pastilla del Asistente."),
]
DOCS = [
    ("CLAUDE.md", "Contexto corto y decisiones vigentes; se carga en cada sesión."),
    ("HISTORIAL.md", "Changelog técnico detallado: el porqué de cada decisión y los bugs con su causa real."),
    ("FLUJO.md", "El ciclo de un cambio: de tu PC a Pruebas y de Pruebas a la demo."),
    ("DESPLIEGUE_RENDER.md · PLAN_ENTORNOS.md", "Infraestructura de los dos servicios y el porqué del modelo."),
    ("PLAN_RAG_CONVENIO.md", "Diseño del piloto de consultas al convenio."),
    ("docs/DASHBOARD.md · docs/ASISTENTE_PANEL.md", "Fichas rectoras del Panel Sindical y del Asistente."),
    ("docs/cct-1875-bancarios.md", "Conceptos del convenio bancario usados para La Bancaria."),
    ("BACKLOG.md · SPRINT_REFORMA.md · GUIA_CODE_REDISENO.md", "Pendientes, el sprint de la reforma laboral y la guía de rediseño."),
]
